"""initial schema

Revision ID: 019f07547146
Revises:
Create Date: 2026-04-28 14:03:17.590897

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "019f07547146"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "facilitator",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "pain_taxonomy",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questionnaire_version",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rationale",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column(
            "priority_factors_addressed", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column(
            "upstream_inputs_referenced", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("language IN ('ar', 'en')", name="rationale_language_valid"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("pain_category_code", sa.String(length=64), nullable=False),
        sa.Column("trigger", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_rule_pain_category_code"), "rule", ["pain_category_code"], unique=False
    )
    op.create_table(
        "pain_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pain_taxonomy_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name_by_language", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "description_by_language", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("example_by_language", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["pain_taxonomy_id"], ["pain_taxonomy.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pain_taxonomy_id", "code", name="pain_category_code_unique_per_taxonomy"
        ),
    )
    op.create_index(
        op.f("ix_pain_category_pain_taxonomy_id"),
        "pain_category",
        ["pain_taxonomy_id"],
        unique=False,
    )
    op.create_table(
        "question",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("questionnaire_version_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("section", sa.String(length=64), nullable=False),
        sa.Column("text_by_language", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mechanic", sa.String(length=32), nullable=False),
        sa.Column("slider_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("branching_rule", sa.Text(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "mechanic IN ('slider', 'single_choice', 'multi_choice', 'free_text', 'ranking', 'branching')",
            name="question_mechanic_valid",
        ),
        sa.ForeignKeyConstraint(
            ["questionnaire_version_id"], ["questionnaire_version.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "questionnaire_version_id", "code", name="question_code_unique_per_version"
        ),
    )
    op.create_index(
        op.f("ix_question_questionnaire_version_id"),
        "question",
        ["questionnaire_version_id"],
        unique=False,
    )
    op.create_table(
        "session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("facilitator_id", sa.UUID(), nullable=False),
        sa.Column("questionnaire_version_id", sa.UUID(), nullable=False),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "phase IN ('discovery', 'decision', 'generation', 'delivered')",
            name="session_phase_valid",
        ),
        sa.ForeignKeyConstraint(["facilitator_id"], ["facilitator.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["questionnaire_version_id"], ["questionnaire_version.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_facilitator_id"), "session", ["facilitator_id"], unique=False)
    op.create_index(
        op.f("ix_session_questionnaire_version_id"),
        "session",
        ["questionnaire_version_id"],
        unique=False,
    )
    op.create_table(
        "answer_option",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.Column("label_by_language", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["question.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "value", name="answer_option_value_unique_per_question"),
    )
    op.create_index(
        op.f("ix_answer_option_question_id"), "answer_option", ["question_id"], unique=False
    )
    op.create_table(
        "decision_scope",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("modules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selected_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "execution_plan",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("ordered_modules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("intersection_pairs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "export_artifact",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column(
            "included_artifacts_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("format IN ('pdf')", name="export_artifact_format_valid"),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_export_artifact_session_id"), "export_artifact", ["session_id"], unique=False
    )
    op.create_table(
        "language_register",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("primary_language", sa.String(length=8), nullable=False),
        sa.Column("arabic_variety", sa.String(length=32), nullable=False),
        sa.Column("register_level", sa.String(length=16), nullable=False),
        sa.Column("cultural_anchors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("derived_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "arabic_variety IN ('msa', 'saudi_dialect', 'not_applicable')",
            name="language_register_arabic_variety_valid",
        ),
        sa.CheckConstraint(
            "primary_language IN ('ar', 'en')", name="language_register_primary_valid"
        ),
        sa.CheckConstraint(
            "register_level IN ('formal', 'semi_formal', 'casual')",
            name="language_register_level_valid",
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_language_register_session_id"), "language_register", ["session_id"], unique=False
    )
    op.create_table(
        "questionnaire_instance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("questionnaire_version_id", sa.UUID(), nullable=False),
        sa.Column("completed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["questionnaire_version_id"], ["questionnaire_version.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questionnaire_instance_questionnaire_version_id"),
        "questionnaire_instance",
        ["questionnaire_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questionnaire_instance_session_id"),
        "questionnaire_instance",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "answer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("questionnaire_instance_id", sa.UUID(), nullable=False),
        sa.Column("question_code", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submitted_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("language IN ('ar', 'en')", name="answer_language_valid"),
        sa.ForeignKeyConstraint(
            ["questionnaire_instance_id"], ["questionnaire_instance.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_questionnaire_instance_id"),
        "answer",
        ["questionnaire_instance_id"],
        unique=False,
    )
    op.create_table(
        "llm_call_record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("language_directive", sa.String(length=8), nullable=False),
        sa.Column("register_id", sa.UUID(), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("called_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint(
            "language_directive IN ('ar', 'en')", name="llm_call_record_language_valid"
        ),
        sa.CheckConstraint(
            "module IS NULL OR module IN ('strategy_theme', 'tone', 'naming', 'slogan', 'tagline')",
            name="llm_call_record_module_valid",
        ),
        sa.CheckConstraint(
            "status IN ('success', 'error', 'timeout')", name="llm_call_record_status_valid"
        ),
        sa.ForeignKeyConstraint(["register_id"], ["language_register.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_llm_call_record_called_at", "llm_call_record", ["called_at"], unique=False)
    op.create_index(
        op.f("ix_llm_call_record_register_id"), "llm_call_record", ["register_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_call_record_session_id"), "llm_call_record", ["session_id"], unique=False
    )
    op.create_table(
        "module_output",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("register_id", sa.UUID(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "upstream_module_outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("rationale_id", sa.UUID(), nullable=False),
        sa.Column("llm_call_record_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("language IN ('ar', 'en')", name="module_output_language_valid"),
        sa.CheckConstraint(
            "module IN ('strategy_theme', 'tone', 'naming', 'slogan', 'tagline')",
            name="module_output_module_valid",
        ),
        sa.ForeignKeyConstraint(["rationale_id"], ["rationale.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["register_id"], ["language_register.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_module_output_rationale_id"), "module_output", ["rationale_id"], unique=False
    )
    op.create_index(
        op.f("ix_module_output_register_id"), "module_output", ["register_id"], unique=False
    )
    op.create_index(
        op.f("ix_module_output_session_id"), "module_output", ["session_id"], unique=False
    )
    op.create_index(
        "ix_module_output_session_module", "module_output", ["session_id", "module"], unique=False
    )
    op.create_table(
        "pain_analysis",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "tagged_pain_categories", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=8), nullable=False),
        sa.Column("register_id", sa.UUID(), nullable=False),
        sa.Column("rationale_id", sa.UUID(), nullable=False),
        sa.Column("llm_call_record_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.CheckConstraint("language IN ('ar', 'en')", name="pain_analysis_language_valid"),
        sa.ForeignKeyConstraint(["rationale_id"], ["rationale.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["register_id"], ["language_register.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pain_analysis_rationale_id"), "pain_analysis", ["rationale_id"], unique=False
    )
    op.create_index(
        op.f("ix_pain_analysis_register_id"), "pain_analysis", ["register_id"], unique=False
    )
    op.create_index(
        op.f("ix_pain_analysis_session_id"), "pain_analysis", ["session_id"], unique=False
    )
    op.create_table(
        "session_system_prompt",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("unified_preamble", sa.Text(), nullable=False),
        sa.Column("module_extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("register_id", sa.UUID(), nullable=False),
        sa.Column("questionnaire_version_id", sa.UUID(), nullable=False),
        sa.Column("pain_analysis_id", sa.UUID(), nullable=False),
        sa.Column("built_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["pain_analysis_id"], ["pain_analysis.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["questionnaire_version_id"], ["questionnaire_version.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["register_id"], ["language_register.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["session_id"], ["session.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        op.f("ix_session_system_prompt_pain_analysis_id"),
        "session_system_prompt",
        ["pain_analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_system_prompt_questionnaire_version_id"),
        "session_system_prompt",
        ["questionnaire_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_system_prompt_register_id"),
        "session_system_prompt",
        ["register_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_system_prompt_register_id"), table_name="session_system_prompt")
    op.drop_index(
        op.f("ix_session_system_prompt_questionnaire_version_id"),
        table_name="session_system_prompt",
    )
    op.drop_index(
        op.f("ix_session_system_prompt_pain_analysis_id"), table_name="session_system_prompt"
    )
    op.drop_table("session_system_prompt")
    op.drop_index(op.f("ix_pain_analysis_session_id"), table_name="pain_analysis")
    op.drop_index(op.f("ix_pain_analysis_register_id"), table_name="pain_analysis")
    op.drop_index(op.f("ix_pain_analysis_rationale_id"), table_name="pain_analysis")
    op.drop_table("pain_analysis")
    op.drop_index("ix_module_output_session_module", table_name="module_output")
    op.drop_index(op.f("ix_module_output_session_id"), table_name="module_output")
    op.drop_index(op.f("ix_module_output_register_id"), table_name="module_output")
    op.drop_index(op.f("ix_module_output_rationale_id"), table_name="module_output")
    op.drop_table("module_output")
    op.drop_index(op.f("ix_llm_call_record_session_id"), table_name="llm_call_record")
    op.drop_index(op.f("ix_llm_call_record_register_id"), table_name="llm_call_record")
    op.drop_index("ix_llm_call_record_called_at", table_name="llm_call_record")
    op.drop_table("llm_call_record")
    op.drop_index(op.f("ix_answer_questionnaire_instance_id"), table_name="answer")
    op.drop_table("answer")
    op.drop_index(op.f("ix_questionnaire_instance_session_id"), table_name="questionnaire_instance")
    op.drop_index(
        op.f("ix_questionnaire_instance_questionnaire_version_id"),
        table_name="questionnaire_instance",
    )
    op.drop_table("questionnaire_instance")
    op.drop_index(op.f("ix_language_register_session_id"), table_name="language_register")
    op.drop_table("language_register")
    op.drop_index(op.f("ix_export_artifact_session_id"), table_name="export_artifact")
    op.drop_table("export_artifact")
    op.drop_table("execution_plan")
    op.drop_table("decision_scope")
    op.drop_index(op.f("ix_answer_option_question_id"), table_name="answer_option")
    op.drop_table("answer_option")
    op.drop_index(op.f("ix_session_questionnaire_version_id"), table_name="session")
    op.drop_index(op.f("ix_session_facilitator_id"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_question_questionnaire_version_id"), table_name="question")
    op.drop_table("question")
    op.drop_index(op.f("ix_pain_category_pain_taxonomy_id"), table_name="pain_category")
    op.drop_table("pain_category")
    op.drop_index(op.f("ix_rule_pain_category_code"), table_name="rule")
    op.drop_table("rule")
    op.drop_table("rationale")
    op.drop_table("questionnaire_version")
    op.drop_table("pain_taxonomy")
    op.drop_table("facilitator")
    # ### end Alembic commands ###
