"""add question constraint fields

Revision ID: 9b3656f425d6
Revises: 019f07547146
Create Date: 2026-04-28 15:57:14.261040

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3656f425d6'
down_revision: str | None = '019f07547146'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('min_selections', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('max_selections', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('free_text_max_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'free_text_max_length')
    op.drop_column('question', 'max_selections')
    op.drop_column('question', 'min_selections')
    # ### end Alembic commands ###
